hostname HQ-RTR # Это меняем на втором роутере на BR-RTR например
service integrated-vtysh-config
!
interface gre1 # Название нашег интерфейса используемого, если назвали по другому - менять
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 qwerty123
!
router ospf
 router-id 1.1.1.1 # Для первого роутера таким и остается, для второго будет 2.2.2.2
 passive-interface default
 no passive-interface gre1
 network 10.10.10.0/30 area 0 # тут сеть, которая будет
 network 192.168.150.0/24 area 0 # Сети, которые так же есть внутри роутера, их добавить, если надо
 network 192.168.200.0/24 area 0
!
log file /var/log/frr/frr.log